var GAME_LEVELS = [
   ["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x dx",
   "x x   2x   x    xxvx",
   "x x  x   c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c <lx   x x",
   "x x^   x   x    xx x",
   "x xu c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxxxx",
    "x@  dxc      c  p  x",
    "xc  vx     <lx    cx",
    "xxxx xxx x   x  xxxx",
    "x    x   x   x     x",
    "x c  x  cxc  x^    x",
    "x    x xxxxx xu c  x",
    "x xxxx  cxc  xxxx  x",
    "xc d x   x  cx     x",
    "x  v x   x xxx c   x",
    "x    x       x    cx",
    "x  c x       x xxxxx",
    "x            xr>  ce",
    "x  c h     <lx     x",
    "xxxxxxxxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxxxxxxxx",
     "xxc    x  d  x   cxx",
     "xcxc   x  v  x  cxcx",
     "x cxc          cxc x",
     "x  cx    x2x   xc  x",
     "x       x   x      x",
     "x         x        x",
     "xr>p  x   @   x f<le",
     "x         x        x",
     "x       x   x      x",
     "x  cx    xfx   xc  x",
     "x cxc          cxc x",
     "xcxc   x  ^  x  cxcx",
     "xxc    x  u  x   cxx",
     "xxxxxxxxxxxxxxxxxxxx"],
     ["xxxxxxxxxxxxxxxxxxxx",
      "x2 xc    d  xc  x  e",
      "x c      v   xc  c x",
      "xx        x   xc  xx",
      "x   ch    x        x",
      "xxxxxx     c    xxxx",
      "xr>          p    cx",
      "x    xxxx  xxxx    x",
      "x      cc        <lx",
      "xxxxxx  c      xxxxx",
      "x        x        cx",
      "xx   cx  x        xx",
      "x c   cx  ^      c x",
      "x@ x   cx u    cx  x",
      "xxxxxxxxxxxxxxxxxxxx"],

      ["xxxxxxxxxxxxxxxxxxxxxxx",
       "xc c cxr> c c cx   c fx",
       "x c c x   xxxxxx   xxxx",
       "xxxx  xp c c dc c  x cx",
       "xf xc xxxxxx vxxxx  c x",
       "x  x  c c  x  x  x   cx",
       "x cxc    xxx  x    xc x",
       "x  xxxx  x    x    xxxx",
       "x c      x    x  xc   x",
       "x        x@ x x  xxxxxx",
       "x cxxx   xxxx xc c   cx",
       "x  xc c c c   xxx  c  x",
       "x ^xxxxxxxxx    xc   cx",
       "x u 2 c c hx    x   <le",
       "xxxxxxxxxxxxxxxxxxxxxxx"]
    ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;